baseURL = "https://harpi.github.io"
languageCode = "en-us"
title = "Breaking Bits"
theme = "terminal"
pagination.pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  
[params.logo]
  logoText = "~/security-researcher"
  logoHomeLink = "/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
[[menu.main]]
  identifier = "htb"
  name = "HTB Writeups"
  url = "/htb"
[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research"
